review
Signed-off-by: Vallari Agrawal <val.agl002@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,7 +15,7 @@ on:
       - 'devel'
   release:
     types:
-      - created
+      - published 
   workflow_dispatch:
     inputs:
       python_version:
@@ -26,14 +26,20 @@ on:
         description: 'PDM Version'
         required: false
         type: string
-      pypi_repo:
-        description: 'Push to test.pypi (dev) or pypi (prod)'
+      pypi_env:
+        description: 'Push to test.pypi (dev) or pypi (prod). And `dev-debug-version` pushes to test.pypi with a test package version.'
         required: true
         default: 'dev'
         type: choice
         options:
           - dev 
-          - prod-and-dev
+          - prod
+          - dev-debug-version
+      # debug_mode:
+      #   description: 'Pushes a debug-release with a "dev<timestamp>"" tag to test pypi.'
+      #               'This is for debugging CI failures - to avoid messing dev/prod releases.'
+      #   required: false
+      #   type: string
 
 env:
   DEFAULT_PYTHON: ${{ inputs.python_version || '3.9' }}
@@ -57,14 +63,18 @@ jobs:
         run: pdm run protoc
       - name: Set current date as env variable
         run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
-      # - name: [debug] Set dev version number    # For debugging CI failures (to avoid messing dev releases)
-      #   run: |
-      #     NEW_VERSION="$(pdm show --version).dev$NOW"
-      #     sed -i "s/^version = \".*\"/version = \"${NEW_VERSION}\"/" pyproject.toml
+      - name: (DEBUG) Set dev version number
+        # Pushes a debug-release to testpypi with "<current_release>dev<timestamp>" version (eg 1.2.15.dev20240710183756)
+        # (to avoid messing current releases versions like 1.2.15).
+        run: |
+          NEW_VERSION="$(pdm show --version).dev$NOW"
+          sed -i "s/^version = \".*\"/version = \"${NEW_VERSION}\"/" pyproject.toml
+        if: (inputs.pypi_env && inputs.pypi_env == 'dev-debug-version')
       - name: Build package
         run: pdm build --config-setting="--build-number=$NOW" --no-sdist
-      - name: Publish package distributions to PyPI
+      - name: Publish package distributions to PyPI ${{ github.event_name }} {{ github.event.action }} ${{ github.event_name == 'release' && github.event.action == 'published' }}
         run: pdm publish --no-build
-        if: startsWith(github.ref, 'refs/tags/') || (inputs.pypi_repo && inputs.pypi_repo == 'prod-and-dev')
+        if: ( github.event_name == 'release' && github.event.action == 'published' ) || (github.event_name == 'workflow_dispatch' && inputs.pypi_env == 'prod') 
       - name: Publish package distributions to Test PyPI
         run: pdm publish --no-build -r testpypi
+        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (inputs.pypi_env == 'dev' || inputs.pypi_env == 'dev-debug-version'))
